name 'MoDajaniCookBook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures MoDajaniCookBook'
long_description 'Installs/Configures MoDajaniCookBook'
version '0.1.0'
